# Generated by Django 4.1 on 2024-01-22 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date_time', models.CharField(max_length=225)),
                ('Booking_status', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='chats',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.IntegerField(max_length=225)),
                ('sender_type', models.CharField(max_length=225)),
                ('receiver', models.IntegerField(max_length=225)),
                ('reciver_type', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=225)),
                ('date_time', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('qualification', models.CharField(max_length=225)),
                ('image', models.CharField(max_length=2000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='login1',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_fname', models.CharField(max_length=225)),
                ('patient_lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('housename', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('blood_group', models.CharField(max_length=225)),
                ('dob', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=225)),
                ('user_lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.login1')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=225)),
                ('end_time', models.CharField(max_length=225)),
                ('schedule_date', models.CharField(max_length=225)),
                ('fee_amount', models.CharField(max_length=225)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='physical_conditions',
            fields=[
                ('physical_condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(max_length=225)),
                ('sugar', models.CharField(max_length=225)),
                ('cholesterol', models.CharField(max_length=225)),
                ('height', models.CharField(max_length=225)),
                ('weight', models.CharField(max_length=225)),
                ('date_time', models.CharField(max_length=225)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.patients')),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.login1')),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=225)),
                ('payment_date', models.CharField(max_length=225)),
                ('payment_type', models.CharField(max_length=225)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.bookings')),
            ],
        ),
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.user'),
        ),
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('available_qty', models.CharField(max_length=225)),
                ('expiry_date', models.CharField(max_length=225)),
                ('rate', models.CharField(max_length=225)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='medicine_prescriptions',
            fields=[
                ('med_pres_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.CharField(max_length=225)),
                ('pres_description', models.CharField(max_length=225)),
                ('p_amount', models.CharField(max_length=225)),
                ('pres_status', models.CharField(max_length=225)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.bookings')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.medicines')),
            ],
        ),
        migrations.CreateModel(
            name='medical_notes',
            fields=[
                ('medical_note_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=225)),
                ('date_time', models.CharField(max_length=225)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.bookings')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.login1'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.patients'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.schedule'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.user'),
        ),
    ]
