# Generated by Django 5.0 on 2024-03-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpapp', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical_conditions',
            name='report',
            field=models.CharField(default=2, max_length=225),
            preserve_default=False,
        ),
    ]
