# Generated by Django 5.0 on 2024-03-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpapp', '0003_physical_conditions_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='physical_conditions',
            name='description',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
