# Generated by Django 4.1 on 2024-03-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpapp', '0004_physical_conditions_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='labtest',
            fields=[
                ('labtest_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.CharField(max_length=225)),
                ('test_name', models.CharField(max_length=225)),
                ('test_description', models.CharField(max_length=225)),
                ('test_amount', models.CharField(max_length=225)),
                ('test_status', models.CharField(max_length=225)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.bookings')),
            ],
        ),
    ]
