# Generated by Django 4.1 on 2024-03-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpapp', '0005_labtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=225)),
                ('lab_phone', models.CharField(max_length=225)),
                ('lab_email', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.login1')),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='lab',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dpapp.lab'),
            preserve_default=False,
        ),
    ]
