# Generated by Django 4.1 on 2024-03-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpapp', '0006_lab_labtest_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=225)),
                ('from_date', models.CharField(max_length=225)),
                ('to_date', models.CharField(max_length=225)),
                ('sub_status', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpapp.user')),
            ],
        ),
    ]
